### ISSUE TITLE
invalidate reputation cache upon registering

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#218]
Currently we fail the invalidate the reputation cache, when a participant registers, which leads to the following bug:

* participant registers, and thereby burns his reputation. reputation cache is not invalidated
* participant fails to attend the meetup

-> in the next meetup, the participant (using the app) will fail to register himself because the rpc does still return the old value, whit the `VerifiedUnlinked` status.

**Comment by brenzi** [comment]
This is a critical bug because it will effectivele prevent someone to register. However, it is not urgent, because:
* we re-synched our rpc nodes on May 22nd from scratch (beginning of ceremony index 3
* not a single reputable registered without showing up for the ceremony this time.
* one bootstrapper did register but didn't show up: 5C86aoJWYuuHxYsi5d74ddJ6tYNhwnLeXHe5qqBWui2cmmPh. what happens in this case? We know who this is and can ask the person to wait before registering if we need to fix this client side. But I believe the app sends no proofofattendance for bootstrappers anyway, does it?

**Comment by clangenb** [comment]
No, the app does send the proof of attendance always if there is one, and the chain always checks it. So a bootstrapper with an invalid PoA can't register. We should fix that on the client side.
