### ISSUE TITLE
Handle meetup splits

### ISSUE THREAD

**Issue by pifragile** [encointer/pallets#230]
If there are two (potentially legit) groups trying to hold the same meetup, because they did not find each other, decide what to do for different group distributions.
If in doubt (eg. if split 50/50), pay rewards to everyone to avoid frustration of legit participants.

**Comment by brenzi** [comment]
watch out: if we rely on the number of correct votes only, this can mean that 8 people vote 5 and get considered for the next steps. this makes no sense.

if 8 people vote 5 and fully attest each other: the meetup is invalid because they didn't follow the rules. But if 3 of the 8 drop out because they have not enough incoming attestations, then the 5 others are legit and should get a reward
Consider the meetup started with 5 people, voting 5 and 3 people come late and get attested anyway 

If the winning vote is 5 and we have two segregated groups of 5 fully attesting each other within their group of 5 (two fully connected graphs with 5 nodes each without connections): Then both groups shall be rewarded to avoid frustration of legit participants

**Comment by brenzi** [comment]
it's a lot easier with the new implementation to reject these split. So, it's better to won't fix: 50:50 will fail
