### ISSUE TITLE
If registering as bootstrapper, the proof of attendance should be ignored or be refunded

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#367]
I just noticed in the app that we register with the proof of attendance even if we are a bootstrapper, but the pallet does not refund it upon unregistering. So we should either refund it if the bootstrapper unregisters, or ignore it when registering, I would vote for the latter.

**Comment by brenzi** [comment]
ignoring the proof upon registering is not easily possible because we only derive bootstrapper status AFTER asserting the proof validity. I'd hesitate to change our runtime logic heavily, because it is well-tested

refunding bootstrappers like reputables seems more straight-forward to me ATM. This however can fail for multiple reasons, like for reputables

However, it ain't the duty of the protocol to fix shortcomings of the client app which may cause extrinsic failures. I'd rather have extrinsics fail if that is more secure and easier to test
