### ISSUE TITLE
Fix assignment when there are not enough locations available

### ISSUE THREAD

**Issue by pifragile** [encointer/pallets#84]
When there are not enough locations available, some participants should not be assigned to a meetup. This can easily be incorporated into `get_meetup_index`.

**Comment by pifragile** [comment]
@brenzi this is the expected behaviour right?

**Comment by clangenb** [comment]
Yes. However, could it be that the current implementation is unfair because the randomized assignment prevents first come-first-served? Or is it even safer to disallow first come-first-served?

Regardless, we recommend anyhow to add more than enough locations when bootstrapping a community. So this theoretical corner-case might not be relevant.

**Comment by brenzi** [comment]
no strict need to be fair as FCFS. just be safe.

**Comment by NicJak** [comment]
The number of assignments (available_slots) is capped by the multiplication of the constant "meetup_multiplier=10u64" with max_num_meetups.. the latter is the minimum number of locations and a prime_below.. thus, as I see it, the number of locations is already limiting the number of assigned participants..

**Comment by brenzi** [comment]
I'm not sure if I get the code right, but while I agree that the number of meetups is capped, this doesn't mean that the participants registrations are cropped to the desired size. Isn't there a wraparound that just causes bigger meetups? Where in the code is the "unregistering" of the excess participants happening?
